Add Homepage Design and Quiz Category Selection
Kendrick-Oppong/quizz-app pull request #1
Opened 2024-11-27 15:24 UTC by Kendrick-Oppong

This PR introduces the following changes:

**Created HomeComponent:**
1. Displays a list of quiz categories (HTML, CSS, JavaScript, Accessibility) with corresponding icons.
2. Uses an EventEmitter to emit the selected category title to the parent component.

**Updated AppComponent:**
1. Injected the QuizService to retrieve quiz data.
2. Defined a property to store the selected quiz category.
3. Initialized the category title property in AppComponent for future dynamic component rendering.

**HTML/CSS Modifications:**

1. Updated the app.component.html and home.component.html templates to reflect the new structure.
2. Added UI elements and visuals for each quiz category.

Here is the UI 
![QuizApp-HOMEPAGE](https://github.com/user-attachments/assets/ac6e2b5e-c98b-4816-aacb-afea68ac90e1)

2024-11-27 17:36 UTC, amt-augustineopokukesse commented on src/app/app.component.ts
> +  selectedCategory: string = '';
Adding the string type in this instance is verbose.. If you initialise a property, as in this case an empty string, TypeScript infers the type from the initialization

2024-11-27 17:38 UTC, amt-augustineopokukesse commented on src/app/components/home/home.component.css
> +  font-size: 1.25rem; /* 20px*/
Why the comment on this line?

2024-11-27 17:38 UTC, amt-augustineopokukesse commented on src/app/components/home/home.component.css
> +  border-radius: 1.5rem; /* 24px*/
remove the comments please

2024-11-27 17:41 UTC, Kendrick-Oppong commented on src/app/components/home/home.component.css
> +  border-radius: 1.5rem; /* 24px*/
OK

2024-11-27 17:41 UTC, amt-augustineopokukesse requested changes
Address the minor changes

2024-11-27 17:41 UTC, Kendrick-Oppong commented on src/app/app.component.ts
> +  selectedCategory: string = '';
OK

2024-11-28 11:54 UTC, amt-augustineopokukesse approved these changes

2024-11-28 12:10 UTC, merged